
- name: Copy composer.json
  copy:
    src: "../../composer.json"
    dest: "{{ server_destination }}"
    force: yes

- composer:
    working_dir: "{{ server_destination }}"
    ignore_platform_reqs: yes

- composer:
    command: update
    working_dir: "{{ server_destination }}"
    ignore_platform_reqs: yes