
- name: Copy composer.json
  copy:
    src: "../../composer.json"
    dest: "{{ server_destination }}"
    force: yes

- name: Setup 'ubuntu' user permissions related to the sync folders
  command: usermod -aG vboxsf ubuntu
  become: yes

- composer:
    working_dir: "{{ server_destination }}"
    ignore_platform_reqs: yes

- composer:
    command: update
    working_dir: "{{ server_destination }}"
    ignore_platform_reqs: yes