
- name: Setup 'ubuntu' user permissions related to the sync folders
  command: usermod -aG vboxsf ubuntu
  become: yes

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  sudo: false